CUDA_VISIBLE_DEVICES=0 python run_glue.py \
--per_gpu_train_batch_size 17 \
--per_gpu_eval_batch_size 17 \
--gradient_accumulation_steps 10 \
--wandb_name mnli-synthesizer-full_att-mix-pretrained-mmae \
--full_att \
--mix \
--albert \
--synthesizer \
--do_train \
--do_eval \
--evaluate_during_training \
--output_dir output/MNLI-mix-pretrained-mmae \
--model_name_or_path albert-base-v2 \
--task_name MNLI \
--learning_rate 3e-5 \
--data_dir data_mnli/MNLI \
--pretrained
