wandb_version: 1

__cached__setup_devices:
  desc: null
  value:
  - cuda
  - 2
_wandb:
  desc: null
  value:
    cli_version: 0.8.36
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
adam_epsilon:
  desc: null
  value: 1.0e-12
albert:
  desc: null
  value: true
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
do_train:
  desc: null
  value: true
evaluate_during_training:
  desc: null
  value: true
fp16:
  desc: null
  value: true
fp16_opt_level:
  desc: null
  value: O1
full_att:
  desc: null
  value: true
gradient_accumulation_steps:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.0001
local_rank:
  desc: null
  value: -1
logging_dir:
  desc: null
  value: null
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 200
max_grad_norm:
  desc: null
  value: 1.0
max_steps:
  desc: null
  value: -1
mix:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
num_train_epochs:
  desc: null
  value: 5.0
output_dir:
  desc: null
  value: output/mnli/full_att
overwrite_output_dir:
  desc: null
  value: false
per_gpu_eval_batch_size:
  desc: null
  value: 17
per_gpu_train_batch_size:
  desc: null
  value: 17
rand_nonatt:
  desc: null
  value: -1.0
save_steps:
  desc: null
  value: 200
save_total_limit:
  desc: null
  value: null
seed:
  desc: null
  value: 42
synthesizer:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: null
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
